version: "3"
services:
#  mongodb:
#    image: mongo:3.2.4
#    container_name: "mongodb-avaliador"
#    ports:
#      - 27017:27017
#    command: --smallfiles
  mongodb:
        image: mongo:3.2.4
        container_name: "mongodb-test"
        ports:
          - 27017:27017
        command: --smallfiles
  app:
    image: pucsp/avaliador
    ports:
      - 8080:8080
    links:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/customer